name: app
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  module1:
    path: ../module1

dev_dependencies:
  lints: ^1.0.0
